#!/usr/bin/env python3
"""Write the updated draft.md to the article directory.

This rewrites the entire draft with corrected technical details:
- UMAP -> t-SNE (openTSNE)
- KMeans -> HDBSCAN
- 8 modes -> 4 modes
- Single HTML -> static site
- Canvas -> WebGL (PixiJS)
- 15 clusters -> 19 clusters
- Updated benchmarks
- New case study data
"""

ARTICLE_DIR = "/Users/nabeel/Dropbox/Spring 2026/ImageSpace Article"

draft = r"""# ImageSpace: A Minimal-Computing Pipeline for Exploratory Visualization of Image Collections

## Abstract

Museums, archives, and libraries have digitized millions of images, yet the analytical tools for examining these collections computationally remain concentrated among scholars with access to GPU infrastructure and machine learning expertise. This paper introduces ImageSpace, a Python-based command-line tool that transforms a folder of images into an interactive static web visualization in which visually and semantically similar images appear near each other, navigable through four distinct modes: t-SNE scatter plots, grids, color sortings, and timelines, with persistent density-based cluster navigation throughout. ImageSpace encodes each image in a 512-dimensional semantic space using CLIP ViT-B/32 via ONNX Runtime, defaulting to CPU with optional hardware acceleration for Apple Silicon and NVIDIA GPUs, then applies PCA and openTSNE dimensionality reduction to project these embeddings into two-dimensional coordinates. HDBSCAN density-based clustering discovers visual groupings automatically, and CLIP generates semantic labels for each cluster. The output is a static website requiring no backend server — built with React and PixiJS WebGL rendering capable of handling over 50,000 images at interactive frame rates. A case study applying ImageSpace to 49,585 paintings from the WikiArt corpus (27 styles, 1,092 artists) demonstrates the tool's analytical value: HDBSCAN discovered 19 clusters with CLIP-generated labels that revealed cross-style formal affinities, made the model's Western-centric biases directly visible (Ukiyo-e woodblock prints concentrated at 97.7% in a single cluster while no Western style achieved comparable concentration), and generated art-historical questions that required domain expertise to interpret. ImageSpace contributes both a reusable method for distant viewing and a design philosophy: that CPU-first processing, zero-dependency output, and multiple visualization modes are principled commitments to accessibility, sustainability, and analytical pluralism rather than concessions to limited resources.

## Plain Language Summary

Many museums, libraries, and archives have scanned their collections and made images available online, but most scholars lack the specialized tools needed to explore visual patterns across thousands of images at once. ImageSpace is a free, open-source tool that takes a folder of images and produces an interactive website where similar images appear near each other. It runs on any laptop without specialized hardware — processing 50,000 images in about 40 minutes on a standard CPU — and the result can be opened in any web browser, shared by email, or hosted on a website with no server required. The tool offers four ways to view a collection: spatial maps showing which images the computer considers similar, timelines arranged by date, color-sorted grids, and browsable galleries. Density-based clusters with automatically generated labels help identify recurring visual groupings. Each view reveals different patterns. In a test with nearly 50,000 paintings from across art history, the tool automatically discovered 19 visual groupings, labeled them using artificial intelligence, and revealed that it treats Japanese woodblock prints as more visually uniform than any Western style — exposing a bias in the underlying computer model. ImageSpace is designed for humanities researchers, museum professionals, and students who want to explore visual collections computationally without writing code or purchasing expensive hardware.

## Keywords

distant viewing; image collections; CLIP embeddings; dimensionality reduction; minimal computing; digital art history

---

## 1. Introduction

Museums, archives, and libraries across the globe have digitized visual collections at a scale that no individual scholar could survey by hand. Europeana aggregates over 50 million cultural heritage objects; the Smithsonian's Open Access initiative, launched in February 2020, released 4.4 million images in a single gesture of institutional generosity. From the Rijksmuseum to the Library of Congress, institutional repositories have published hundreds of thousands of high-resolution scans. The analytical capacity to study these collections computationally, however, remains concentrated among scholars who possess GPU hardware, Python fluency, and familiarity with machine learning workflows. Digitized collections thus reproduce the exclusions of analog scholarship in digital form: access to the images has been democratized, but access to the methods for analyzing them has not. The digital archive promises universal availability while its analytical instruments enforce disciplinary specialization; the images are open, but the means of seeing through them remain closed.

The tools available for computational image analysis (deep learning classifiers, feature extraction pipelines, similarity search engines) were designed for computer science evaluation regimes where images are datasets and success is measured by accuracy against ground-truth labels. Running these tools requires GPU hardware costing thousands of dollars, Python environments with complex dependency chains, command-line fluency, and operational familiarity with frameworks such as PyTorch or TensorFlow. The outputs are matrices, classification scores, and log files, not explorable interfaces that invite humanistic inquiry. These requirements are not incidental. They encode what Wasielewski (2023) identifies as computational formalism's epistemological assumption: that images are data points awaiting correct categorical assignment rather than cultural objects requiring situated interpretation. The question is whether the tools currently available to humanities scholars ask the right questions, not whether those tools can analyze images at all.

This paper introduces ImageSpace, a command-line tool that takes a folder of images and produces an interactive static website in which visually and semantically similar images appear near each other, navigable through four visualization modes with persistent density-based cluster navigation. Designed for humanities scholars, museum professionals, and students who work with visual collections without GPU infrastructure or machine learning expertise, the pipeline uses CLIP ViT-B/32 embeddings via ONNX Runtime, defaulting to CPU inference, to encode each image in a 512-dimensional semantic space, then applies PCA pre-reduction and openTSNE (Policar et al. 2019) to project these embeddings into two-dimensional coordinates. HDBSCAN (Campello et al. 2013) discovers density-based clusters automatically, and CLIP generates semantic labels for each discovered grouping. An optional `--gpu` flag enables hardware acceleration (CoreML on Apple Silicon, CUDA on NVIDIA GPUs) for users who have it, but the tool never requires it. The output viewer renders all visualizations using PixiJS WebGL, handling over 50,000 images at interactive frame rates with no external dependencies or backend server. Every design decision reflects a commitment to accessibility and sustainability that treats hardware acceleration as a welcome addition rather than a baseline assumption: CPU-first processing as the default, static output, multiple visualization modes. ImageSpace demonstrates that computational visual analysis can be practiced by any scholar with a laptop and an image folder, and that the plurality of views the tool affords invites richer inquiry than any single mode of computational seeing.

The article proceeds through five sections. "Context" situates ImageSpace within the scholarly conversations it addresses: distant viewing, minimal computing, and the epistemology of computational image analysis. "Related Software" positions the tool among existing visualization and analysis platforms. "Development Methodology" describes the pipeline's architecture, the reasoning behind its key design choices, and a case study applying the tool to 49,585 paintings from the WikiArt corpus. "Audience" identifies intended users and acknowledges the tool's constraints. "Impact" argues for ImageSpace's contribution to computational humanities. Through each section, the paper contends that certain constraints (CPU-first processing, static output, multiple partial views) are principled commitments rather than deficiencies, while other limitations (CLIP's training biases, the absence of annotation features) are genuine tradeoffs that define the tool's appropriate scope.

## 2. Context

Distant viewing has achieved theoretical maturity while remaining practically unavailable to most of its intended practitioners. The concept, which Arnold and Tilton (2023) define as a method for discovering visual patterns invisible at the scale of individual images, descends from Moretti's (2013) distant reading, where "distance, let me repeat it, is a condition of knowledge: it allows you to focus on units that are much smaller or much larger than the text" (48–49). Arnold and Tilton adapt this for the visual domain, arguing that images require distinct computational treatment because, unlike text, they must first be interpreted before they can be processed: a semantic gap between pixel values and cultural meaning that no model closes automatically. Manovich's (2012) pioneering "How to Compare One Million Images?" demonstrated that visual collections could be arranged by computationally extracted features, revealing stylistic trends and compositional patterns across entire corpora, yet that demonstration required custom scripts, server-grade hardware, and expertise in image processing that few humanities departments possess. In the fifteen years since, significant theoretical refinement has followed (Wasielewski 2023; Impett and Offert 2024), but distant viewing remains a practice concentrated among scholars at well-resourced institutions. Moretti's (2013) challenge about "sharing raw materials" (240) was institutional: the infrastructure for distant reading had to be collective, not individual. ImageSpace's individual-laptop model addresses one barrier (hardware requirements) while leaving the larger institutional challenge intact; the concept circulates widely, but the capacity to enact it does not.

The primary obstacle to widespread adoption is not methodological skepticism but infrastructure. The tools that enable computational visual analysis (convolutional neural networks, transformer architectures, embedding extraction pipelines) presuppose GPU hardware, Python environments with complex dependency chains, and operational knowledge of machine learning frameworks. Yet the assumption that CPU inference is impractically slow deserves scrutiny: ONNX Runtime processes CLIP embeddings at approximately 46 images per second on a modern laptop CPU, meaning a collection of 50,000 images completes in under 20 minutes of embedding time — a far cry from the hours-long waits that characterized earlier CPU-based pipelines. Gil and Ortega (2016) formalize the infrastructure asymmetry through the concept of minimal computing: a recognition that assumptions about universal access to identical computational resources reproduce global inequities within digital scholarship. ImageSpace draws on this principle while acknowledging the distance between its deployment (a laptop in a university office) and the extreme resource constraints Gil and Ortega primarily address in the Global South. The alignment is in the design premise, not the material circumstance: both insist that tools should be designed for the hardware scholars actually possess rather than the hardware tool-builders wish they possessed. ImageSpace asks what computational image analysis looks like when it assumes no GPU, no server, and no departmental IT support, and in answering that question, it expands who counts as a potential practitioner of distant viewing.

Beyond infrastructure, existing tools embed epistemological assumptions that conflict with humanities inquiry. Computer vision benchmarks evaluate images against ground-truth labels: classification accuracy, precision, recall, F1 scores. This evaluation regime assumes that the categories of analysis pre-exist the encounter with the collection, that the scholar's task is to confirm rather than discover. Drucker (2013) argues that digital art history must develop computational methods adequate to its objects, methods that preserve ambiguity, support multiple interpretations, and resist reducing visual complexity to quantitative scores. Art objects pose particular challenges: they are polysemous, culturally situated, and their significance often resides in qualities (materiality, intentional ambiguity, art-historical provenance) that resist the feature spaces of vision-language models. Wasielewski's (2021) diagnosis of digital art history's "growing pains" identifies a recurring pattern in which humanities scholars adopt computer science tools wholesale, inheriting design assumptions that conflict with interpretive practices. ImageSpace's outputs (scatter plots, density-based clusters with semantic labels, color sortings, filtered subsets) are starting points for humanistic inquiry rather than endpoints; they generate questions about what the collection contains rather than answering predetermined ones. The tool's design reflects the premise that computational image analysis for the humanities requires a different relationship between tool and scholar: one in which the tool provokes and the scholar interprets.

## 3. Related Software

Several tools address the visualization of image collections computationally, each encoding particular assumptions about infrastructure, audience, and the relationship between computation and interpretation. To our knowledge, no existing tool combines CLIP-based semantic embeddings, multiple visualization modes, density-based clustering with automatic labeling, and zero-dependency static output in a single package. PixPlot (Duhaime 2019), developed at the Yale Digital Humanities Lab, is the closest technical comparator: it uses InceptionV3 embeddings, a 2015-era convolutional neural network producing 2,048-dimensional feature vectors, to project image collections into two-dimensional space via UMAP, rendering the result as a WebGL-based browser visualization with automatic hotspot clustering. PixPlot requires a local web server, depends on TensorFlow and Python 3.7 (now end-of-life), and offers a single visualization mode: the two-dimensional scatter plot. Its last release was February 2020; the tool is effectively unmaintained. The design reflects the assumptions of its era: that CNN features sufficed for similarity, that a single scatter view was adequate for exploration, and that server dependencies were acceptable overhead. Its abandonment illustrates a sustainability pattern discussed below, in which tools built on heavy dependency chains are vulnerable to the ecosystem they depend on.

Vikus Viewer (Glinka, Pietsch, and Dörk 2017) takes a fundamentally different approach, arranging collections by structured metadata (temporal attribution, keyword categories) on a zoomable canvas that moves seamlessly from collection overview to individual item detail. The authors frame their work as reconciling "the perpetuated antagonism between qualitative and quantitative methods of distant and close viewing" and argue for "cultural sensitivity" in tool design: the principle that "the cultural content, meaning, and specific qualities of a collection and its items would be the driving force." They explicitly flag similarity-based layouts using neural embeddings as future work, precisely the design ImageSpace implements. Whitelaw (2015), whose "generous interfaces" concept undergirds both Vikus Viewer and ImageSpace, argues that search-box-first interfaces actively impoverish the user's encounter with collections because they "withhold information" and force premature query formulation. In the same field, Arnold et al. (2020) produced a generous interface for a spatiotemporal photo collection; Huang and Lee's (2025) Digital Collections Explorer enables multimodal search but requires a server backend; VISAtlas (Ye et al. 2024) uses neural image embeddings for specialized visualization. These tools share a commitment to making visual collections computationally navigable, yet each requires server infrastructure, a build step, or structured metadata that must be curated before the tool can function. The server requirement, in particular, ensures that the scholar who lacks institutional IT support cannot use these tools at all, reproducing the infrastructure asymmetry the generous-interface tradition claims to resist.

ImageSpace inherits from both lineages: from PixPlot, the use of neural embeddings to arrange images by computational similarity rather than human-curated metadata; from Vikus Viewer, the commitment to generous, overview-first, browsable design. It departs from both by dispensing with the search box entirely, instead privileging spatial browsing over query-driven retrieval in a manner consistent with Whitelaw's (2015) argument that search "withholds information." The user encounters the collection through visual arrangement, not through query formulation. ImageSpace also responds to Glinka, Pietsch, and Dörk's (2017) cultural-sensitivity principle, though imperfectly: its reliance on CLIP embeddings means the arrangement is driven by the model's training data, not by the cultural content of the collection itself. The color-sorting mode partially recovers this sensitivity by arranging images according to their own visual properties rather than learned associations, but the tension between model-driven and content-driven arrangement is real and should not be resolved by pretending it does not exist. ImageSpace's static website output, requiring no backend server and no external dependencies beyond a web browser, addresses a need none of these tools was designed to fill: the scholar working alone, offline, with an image folder and a laptop.

The release of CLIP (Radford et al. 2021) transformed computational image analysis by training a model to link images and text in a shared semantic space, enabling similarity computations that capture conceptual as well as purely visual relationships. Strafforello et al. (2024) tested whether large vision-language models have "mastered art history" and found significant limitations in period and style attribution; Asperti et al. (2025) examined whether CLIP perceives art as humans do; Rashtchian et al. (2023) analyzed what image embeddings encode, distinguishing the model's sensitivity to "substance" (iconographic content, compositional structure) from its relative blindness to "style" (brushwork, palette, medium). ImageSpace uses CLIP ViT-B/32 through ONNX Runtime, a CPU-optimized inference engine, with a graceful fallback to color-histogram embeddings when the CLIP model is unavailable. The choice of ViT-B/32 balances inference speed on CPU (the smallest CLIP variant, fast enough for commodity hardware) with embedding quality sufficient for humanities-relevant similarity judgments; alternatives such as DINOv2 (self-supervised, no text alignment) or larger CLIP variants would require heavier models or different inference pipelines without clear gains for the target use case. A CPU-optimized inference engine carrying state-of-the-art vision-language capabilities extends the reach of these models to scholars whose hardware would otherwise exclude them.

A critical limitation accompanies this choice. CLIP was trained on internet image-text pairs scraped predominantly from English-language web sources, and its semantic space reflects the biases of that corpus. Agarwal et al. (2021) document these biases systematically: in FairFace experiments, Black individuals were misclassified into denigrating non-human categories at approximately 14% (versus under 8% for other groups), and crime-related misclassification varied sharply by race (Indian 24.9%, Latino 24.4%, White 10.8%). Crucially, "class design" (the mere choice of available labels) radically redistributed these biases, meaning that CLIP's similarity space carries socially loaded associations structurally, even when no explicit labels are applied. When ImageSpace arranges cultural heritage images by CLIP similarity, it imposes these biases on the collection. Scholars working with non-Western, indigenous, or culturally specific materials should be aware that the embedding space privileges Western visual and textual conventions. The color-histogram fallback bypasses CLIP's training-data biases but introduces its own limitations: it reduces images to chromatic properties, discarding all semantic and compositional information, and its HSL color space reflects particular conventions in color science. The tension between semantic richness and bias is genuine, and ImageSpace's design makes that tension visible rather than resolving it.

The sustainability of research software in the humanities is a documented concern. Anzt et al. (2020) survey the infrastructure required for sustainable research software in Germany and beyond, identifying institutional support and simple architectures as key to longevity. Guo (2021), reflecting on Python Tutor's decade of sustained use by ten million users, identifies design simplicity as the single most important contributor to a tool's survival. Konkol et al. (2020) examine the infrastructure gap for reproducible scholarly communication. ImageSpace addresses sustainability through a deliberate architectural choice: the viewer is a static website built with standard web technologies (HTML, CSS, JavaScript) that requires no backend server, no package manager, and no dependency updates to run. The output uses WebP image atlases and binary data formats that any modern browser can render. Because no server process must remain running and no dependency chain must be maintained, a viewer produced today will open in a browser ten years from now. Durability through limitation — by requiring no backend infrastructure, the tool remains functional long after more complex software has succumbed to dependency rot.

## 4. Development Methodology

ImageSpace processes image collections through nine sequential stages, each implemented as an independent module that can be replaced or extended without altering the pipeline's overall logic. Stage 1 (Image Discovery) recursively scans an input directory for supported formats (JPEG, PNG, GIF, BMP, WebP), skipping hidden files and system directories. Stage 2 (Atlas Generation) creates WebP atlas spritesheets — composite images at 4096 by 4096 pixels containing 128-pixel thumbnails — at approximately 115 images per second, replacing the individual-thumbnail approach with a format that enables efficient WebGL texture loading. Stage 3 (Embedding Extraction) encodes each image into a 512-dimensional vector using CLIP ViT-B/32 via ONNX Runtime, with automatic fallback to color histograms if the CLIP model cannot be loaded. Stage 4 (Layout and Clustering) first applies PCA to reduce the 512-dimensional embeddings to 50 dimensions (retaining approximately 69% of variance), then uses openTSNE with FFT acceleration (Policar et al. 2019) to project these into two-dimensional coordinates, and finally applies HDBSCAN (Campello et al. 2013) for density-based clustering — discovering the number of visual groupings automatically rather than requiring a pre-specified cluster count, with noise points reassigned to the nearest cluster via cKDTree distance. Stage 5 (k-Nearest Neighbors) computes the ten most similar images for each image using cosine similarity on the 50-dimensional PCA embeddings. Stage 6 (Cluster Labels) uses CLIP to generate semantic labels for each discovered cluster by scoring candidate descriptions against cluster centroids. Stage 7 (Metadata Extraction) records dominant colors and parses timestamps from filenames. Stage 8 (Image Features) computes brightness (BT.601 luminance), visual complexity (Shannon entropy), and edge density (Sobel magnitude), each normalized to a 0–100 scale. Stage 9 (Output) writes binary data files (24 bytes per image), metadata CSV, neighbor indices, and cluster labels. Each stage is encapsulated in a separate module, allowing researchers to substitute a different embedding model, a different reduction algorithm, or a different output format while preserving the pipeline's structure. This modularity separates what the machine computes from how the scholar interprets, ensuring that changes in one domain do not destabilize the other.

Running CLIP inference on CPU is slower than GPU inference, yet the magnitude of this difference has narrowed considerably with optimized inference engines. ONNX Runtime is configured with graph-level optimizations and memory arena controls; on an Apple M-series laptop, it processes approximately 46 images per second on CPU alone. An optional `--gpu` flag auto-detects available hardware acceleration (CoreML on Apple Silicon via the Neural Engine, CUDA on NVIDIA GPUs) and engages it when present, falling back to CPU otherwise. This design instantiates the minimal computing principle within machine learning inference: rather than assuming the user possesses a GPU, ImageSpace assumes they do not and designs accordingly. The `--gpu` flag permits acceleration without mandating it, preserving the tool's accessibility guarantee while acknowledging that some users have hardware capable of faster processing. In the WikiArt case study below, CPU-only processing for 49,585 images completed in 40.7 minutes total — including atlas generation, embedding extraction, dimensionality reduction, clustering, and feature computation. Both CPU and GPU paths produce identical embeddings and identical visualizations. What matters is what the default assumes: a tool that defaults to GPU and degrades on CPU treats accessibility as an afterthought; a tool that defaults to CPU and optionally accelerates treats it as a design premise.

The ImageSpace viewer functions as an analytical instrument, not a display layer applied after computation, offering multiple modes of engagement with the collection. Whitelaw (2015) argues that generous interfaces must provide "multiple, fragmentary representations to reveal the complexity and diversity of cultural collections"; Drucker, as Whitelaw cites, calls this "parallax," an "open-ended proliferation of partial views" rather than a single definitive representation. ImageSpace instantiates this principle through four modes. The t-SNE Scatter positions images by their openTSNE projection, revealing embedding-space neighborhoods and cluster structure, with a minimap for orientation within large collections. Grid provides a browsable gallery view. Color sorts images by HSL-derived dominant hue. Timeline arranges images chronologically when metadata dates are supplied. Across all four modes, HDBSCAN density-based clusters appear as persistent navigation cards in a sidebar, each bearing its CLIP-generated semantic label — "Baroque," "Seascapes," "Abstract Expressionist," "Portraits — Close-up" — allowing the scholar to move between cluster-level and collection-level views without switching modes. A detail panel displays each selected image at full resolution alongside its ten most similar neighbors (computed via cosine similarity), metadata, and computed visual features. Categorical dropdown filters and continuous range sliders (brightness, complexity, edge density, outlier score, cluster confidence) enable the scholar to isolate subsets for closer examination. Each mode answers a different question: scatter plots ask "what is semantically similar?"; color asks "what is the chromatic structure of this collection?"; clusters ask "what are the recurring visual groupings, and what does the model call them?" This plurality instantiates what Moretti (2013) describes as the epistemology of distance: "reality is infinitely rich; concepts are abstract, are poor. But it's precisely this 'poverty' that makes it possible to handle them, and therefore to know" (49). Each mode is a deliberate reduction that, precisely through what it discards, renders specific patterns visible. Understanding a visual collection requires several partial representations, each surfacing patterns the others obscure, and this multiplicity, in Whitelaw's (2015) words, "emphasises a human interpretive process" rather than algorithmic finality.

ImageSpace emerged from iterative development at the intersection of digital humanities research and software engineering, a position that allowed design decisions to be evaluated against both technical constraints and scholarly needs. The tool was tested with art collections (finding stylistic clusters in museum holdings), historical press photographs (identifying temporal visual trends), architectural photography (compositional analysis across building types), and the WikiArt corpus described below. Documentation includes a step-by-step vignette for processing art collections and a plain-language technical explanation, both designed to support scholars without programming backgrounds. A Google Colab notebook provides an alternative processing path for scholars who prefer not to install software locally. No formal user study has been conducted; structured evaluation with art historians and museum professionals is planned as future work. This iterative design practice, in which each technical decision is also an interpretive claim about what visual analysis requires, models a reflexive stance that should characterize computational humanities tool development more broadly.

To demonstrate how ImageSpace translates computational analysis into interpretable visual patterns, the tool was applied to a proportional sample of 49,585 paintings from the WikiArt corpus (Saleh and Elgammal 2015), spanning 1,092 artists and 27 art-historical style categories from Early Renaissance to Minimalism. Processing on an Apple M-series laptop using CPU only completed in 40.7 minutes total: atlas generation in 7.2 minutes, CLIP embedding extraction in 18.1 minutes (45.7 images per second), openTSNE projection in 26 seconds, and HDBSCAN clustering in 19 seconds. The t-SNE scatter view revealed 19 distinct clusters discovered automatically by HDBSCAN (Figure 1), each assigned a semantic label generated by CLIP. Unlike KMeans, which requires the analyst to pre-specify the number of clusters, HDBSCAN determines the cluster count from the density structure of the data itself — a distinction that matters for exploratory analysis, where the point is to discover structure rather than impose it.

![t-SNE projection of 49,585 WikiArt paintings encoded with CLIP ViT-B/32, colored by HDBSCAN cluster assignment. Nineteen density-based clusters are visible, each with a CLIP-generated semantic label. The Ukiyo-e concentration is visible at the periphery.](figures/fig1_tsne_clusters.png)
*Figure 1. t-SNE projection of 49,585 WikiArt paintings encoded with CLIP ViT-B/32, colored by HDBSCAN cluster. Nineteen clusters with CLIP-generated labels reveal visual groupings that cut across art-historical period boundaries.*

CLIP embeddings grouped art by formal visual properties rather than the period labels art historians conventionally assign. Cluster 3, the largest (n=6,903), combined Baroque (19.4%), Northern Renaissance (11.4%), Romanticism (10.9%), and Early Renaissance (10.8%), producing a grouping in which Albrecht Dürer's detailed Northern engravings sit beside Caravaggio's dramatic chiaroscuro and Raphael's balanced High Renaissance compositions — figurative art bound together by shared formal properties (figural composition, dark-ground portraiture, oil technique) that persist across what art history treats as distinct movements. This confirms Rashtchian et al.'s (2023) finding that embeddings encode "substance" (content, compositional structure) more reliably than "style" (period-specific technique or artistic program). That four centuries of European figurative painting collapsed into a single computational neighborhood, labeled "Baroque" by CLIP's own semantic assessment, suggests the model detects a continuity in Western representational convention that art-historical periodization actively works to obscure. HDBSCAN's finer granularity also proved revealing: where a coarser clustering might absorb all landscape painting into a single group, HDBSCAN distinguished "Vast Landscapes — Romantic Landscapes" (Cluster 5), "Vast Landscapes — Mountain Landscapes" (Cluster 6), "Romantic Landscapes" (Cluster 11), "Vast Landscapes — Impressionist" (Cluster 18), and "Seascapes" (Cluster 17) — five distinct landscape clusters reflecting different compositional traditions, each with its own CLIP-generated label. The cluster composition heatmap (Figure 3) quantifies these cross-style affinities across all 19 clusters.

![Heatmap showing the style composition of each of the 19 HDBSCAN clusters. Rows represent clusters; columns represent art-historical styles. Color intensity indicates the proportion of each style within a cluster.](figures/fig3_cluster_heatmap.png)
*Figure 3. Cluster composition heatmap for 19 HDBSCAN clusters across 27 art-historical styles. Most clusters contain multiple styles, confirming that CLIP groups art by formal visual properties rather than period labels.*

A second finding reinforces this pattern at the opposite end of the art-historical timeline. Cluster 16, the second largest (n=7,185), united Abstract Expressionism (21.6%), Color Field Painting (13.6%), Expressionism (12.3%), and Minimalism (11.5%), with Rothko's color fields adjacent to Pollock's drip paintings — abstract-adjacent styles sharing visual properties (large non-representational areas, high color saturation, geometric or gestural fields) that the embedding space recognizes as a coherent formal family, labeled "Abstract Expressionist" by CLIP. Meanwhile, Cluster 15 (n=1,219) isolated Cubism at 53.1% alongside Expressionism (15.5%) and Synthetic Cubism (8.9%), demonstrating that HDBSCAN's density-based approach can detect both broad groupings and more specific stylistic islands that a fixed cluster count might miss.

The case study's most significant finding, however, concerns what CLIP fails to discriminate. Of all Ukiyo-e prints in the dataset (n=726), 97.7% (709 images) were assigned to a single cluster (Cluster 0), while only 17 Ukiyo-e images were distributed across the remaining 18 clusters. Hokusai's landscapes, Hiroshige's rain scenes, and Utamaro's bijin-ga portraits all collapsed together despite their considerable art-historical diversity, while Western styles of comparable visual range (Impressionism, Realism) were distributed across multiple clusters. CLIP treated Japanese woodblock prints as visually interchangeable while distributing Western styles across formally nuanced groupings, a direct manifestation of the Western-centric training biases Agarwal et al. (2021) documented. ImageSpace makes these biases structurally visible: what might remain an abstract statistic in Agarwal et al.'s audit becomes an observable pattern in the scatter plot, where one can see the Ukiyo-e concentration against the dispersed Western groupings (Figure 2), furnishing the kind of evidence that the CFP's call for work demonstrating "the limits of computational approaches" explicitly solicits.

![Detail of the t-SNE projection showing the Ukiyo-e concentration in Cluster 0 at the periphery of the embedding space. Of 726 Ukiyo-e prints, 709 (97.7%) were assigned to this single cluster.](figures/fig2_ukiyoe_isolation.png)
*Figure 2. Ukiyo-e cluster concentration in the t-SNE projection. The near-total concentration (97.7%) contrasts with Western styles distributed across multiple clusters, making CLIP's training bias directly visible.*

The tool did not classify these images; it arranged them in ways that prompted questions no manual inspection of 49,585 paintings could have generated. Why does CLIP group four centuries of figurative art into one neighborhood while distinguishing five distinct landscape traditions? Why does it isolate Ukiyo-e but distribute Impressionism across four separate clusters? Why does HDBSCAN discover 19 groupings where a human curator might have expected 27 (the number of art-historical style labels in the dataset)? These questions demand art-historical expertise, contextual knowledge, and interpretive labor that no scatter plot can supply. This is distant viewing as Arnold and Tilton (2023) define it: a computational arrangement that provokes inquiry rather than settling it.

## 5. Audience

The primary audience for ImageSpace consists of humanities scholars who work with image collections (digital humanists, art historians, museum professionals, visual culture researchers) and who seek computational methods without the overhead of establishing machine learning environments. The tool assumes no GPU, no server, and no Python expertise beyond installing a package and running a single command. An optional `--gpu` flag accelerates processing on compatible hardware but is never required. The outputs, static websites, can be opened in any web browser, shared via email, hosted on GitHub Pages, or embedded in course materials. Guo (2021) identifies this kind of low-barrier entry as the single most important contributor to a research tool's adoption beyond its creators.

This accessibility is a principled position about who should be able to practice computational humanities, not an incidental feature of the software's architecture. The same low-barrier design extends to pedagogy: the tool's zero-configuration workflow makes it suitable for classroom use in digital humanities courses, where students can process their own collections and compare visualization modes without managing dependencies or writing code. By lowering the entry barrier to distant viewing, ImageSpace expands the community of scholars who can engage computationally with visual collections, and this expansion matters because the questions computational tools generate depend on who is asking them.

ImageSpace's WebGL rendering engine (PixiJS 8) handles collections of over 50,000 images at interactive frame rates — approximately 30 frames per second in testing with 49,585 WikiArt images on a standard laptop. CPU-only embedding extraction, the default, processes approximately 46 images per second via ONNX Runtime, meaning a 5,000-image collection completes embedding in under two minutes and a 50,000-image collection in approximately 18 minutes. The full pipeline (including atlas generation, feature computation, and clustering) completed in 40.7 minutes for 49,585 images on an Apple M-series CPU. The static website output uses WebP atlas textures and binary data formats, producing compact files that load efficiently in any modern browser. These performance characteristics result from deliberate architectural decisions: WebGL sprite batching over Canvas pixel manipulation, binary data over JSON, atlas textures over individual thumbnails.

As documented in §3, CLIP embeddings carry structural biases from their training corpus. Every scatter plot ImageSpace produces is an arrangement shaped by English-language internet image-text pairs, and the visual authority of a spatial layout can make those biases appear natural. When a cluster of non-Western artworks appears "similar" according to CLIP, the similarity may reflect Western stereotyping rather than art-historical affinity. More fundamentally, visualization itself has limits as a mode of knowing art: a scatter plot cannot capture provenance, materiality, or intentional ambiguity; it captures only the relationships the embedding model was trained to detect. The tool surfaces patterns but cannot, on its own, distinguish meaningful patterns from artifacts of the model's training. Close looking, contextual knowledge, and domain expertise remain essential. Some of the tool's constraints are generative (CPU-first processing extends the user base, static output ensures longevity, optional acceleration respects users' actual hardware); others are genuine limitations that define its appropriate scope: collections and questions typical of humanities research rather than industrial computer vision. The absence of annotation and collaborative features reflects architectural scope rather than principled minimalism.

## 6. Impact

The case study and technical architecture together demonstrate that ImageSpace contributes a reusable method for exploratory visualization of art and image collections, one whose value lies in the quality of questions it generates rather than in classification accuracy. After the technical architecture (§4) and its honest constraints (§5), this contribution can be stated with greater specificity than the introduction allowed. ImageSpace contributes a specific kind of distant viewing: one that arranges images by learned semantic similarity, discovers density-based clusters and labels them automatically, offers multiple partial views of that arrangement, and produces results that require the scholar's interpretive labor to become meaningful. In the WikiArt case study, this was illustrated concretely: the scatter plot's 19 clusters, the automatically generated semantic labels, and the style-mixing patterns each surfaced questions that demanded art-historical interpretation rather than providing answers. By packaging this workflow into a reusable, zero-dependency pipeline, ImageSpace makes it possible for scholars without machine learning infrastructure to perform exploratory analysis on their own collections, comparing visual corpora, tracking stylistic patterns, and identifying unexpected formal affinities that manual inspection at scale could never surface. The tool demonstrates distant viewing as a viable, working research practice for scholars who previously lacked the technical resources to attempt it.

Beyond the software, ImageSpace embodies a design philosophy that computational humanities would benefit from adopting more broadly. Minimal computing (no GPU required, no backend server) responds to the global access inequities Gil and Ortega (2016) identify, and static-first architecture (sustainability through simplicity) responds to the research software abandonment Anzt et al. (2020) and Guo (2021) document. If computational humanities tools are to serve the breadth of the scholarly community rather than its most technically resourced fraction, they must be designed with the constraints of actual humanities practice in mind: ordinary hardware, portable outputs, and the scholar's interpretive capacity treated with the same seriousness as the algorithm's computational power.

The four visualization modes respond to a different problem: the reductiveness of single-metric evaluation that Drucker (2013) critiques. Where a classification pipeline produces one answer, ImageSpace produces four partial views of the same collection, each constructing a different account of what the collection contains, while persistent cluster navigation with CLIP-generated labels provides a consistent analytical vocabulary across all views. This multiplicity speaks directly to the recognition that art is, as the CFP for this special issue frames it, "a dynamic site where meanings are constructed, contested, and circulated": different computational arrangements construct different meanings from identical material, and the scholar's task is to interpret the differences. A tool that offers only one view of a collection implies that one computational arrangement suffices; a tool that offers four views with nineteen labeled clusters insists that representation is always partial, and that the scholarly act lies in reading across the gaps between views.

Future development could extend ImageSpace's embedding layer to support multimodal search (finding images by text query), incorporate annotation workflows for collaborative use, and expand the filtering capabilities to include user-defined metadata categories. Each extension would need to preserve the tool's founding commitments (CPU-first default, zero-dependency output, static site portability) or explicitly argue for the tradeoff. ImageSpace joins a growing body of computational humanities tools that take their own design as an object of scholarly reflection: tools whose architecture embodies arguments about what computation can and should do in humanities research, and whose limitations are stated as clearly as their capabilities. The images are open, and the means of seeing through them can be open too, provided the tools are designed to treat accessibility as a scholarly commitment rather than a secondary convenience; whether CPU-first design can extend beyond embedding-and-projection workflows to more computationally demanding methods remains an open question that the field must answer collectively.

---

## Acknowledgements

[To be completed.]

## Authorship Contribution Statement (CRediT)

[Author]: Conceptualization, Methodology, Software, Writing — Original Draft, Writing — Review & Editing, Visualization, Data Curation.

## Conflict of Interest Statement

The author declares no conflicts of interest.

## Funding Disclosure Statement

[To be completed.]

## Data Availability Statement

ImageSpace source code is available at [repository URL] under an open-source license, with a persistent identifier via Zenodo. The WikiArt corpus used in the case study is publicly available through Kaggle. The ImageSpace output files (visualization, cluster data) for the case study described in this paper are archived at [DOI].

## Glossary

- **CLIP**: Contrastive Language-Image Pre-training, a neural network trained by OpenAI that embeds images and text in a shared 512-dimensional semantic space, enabling similarity computations that capture both visual and conceptual relationships (Radford et al. 2021).
- **t-SNE**: t-distributed Stochastic Neighbor Embedding, a dimensionality reduction algorithm that preserves local neighborhood structure when projecting high-dimensional data into two dimensions for visualization (van der Maaten and Hinton 2008). ImageSpace uses the FFT-accelerated openTSNE implementation (Policar et al. 2019).
- **HDBSCAN**: Hierarchical Density-Based Spatial Clustering of Applications with Noise, a clustering algorithm that discovers groupings of varying density without requiring the number of clusters to be specified in advance (Campello et al. 2013).
- **PCA**: Principal Component Analysis, a linear dimensionality reduction technique used as a pre-processing step to reduce CLIP's 512-dimensional embeddings to 50 dimensions before t-SNE projection.
- **Embedding**: A numerical vector representing an image's visual and semantic properties in high-dimensional space; two images with similar embeddings are judged "similar" by the model that produced them.
- **Dimensionality reduction**: A mathematical technique for projecting high-dimensional data (such as 512-dimensional CLIP embeddings) into two or three dimensions suitable for visual inspection.
- **Distant viewing**: A method for computational analysis of visual media at scale, analogous to Moretti's distant reading of textual corpora, in which patterns are discovered through computational arrangement rather than individual inspection (Arnold and Tilton 2023).
- **ONNX Runtime**: An inference engine that runs pre-trained machine learning models on CPU, with optional hardware acceleration, without requiring the original training framework.
- **Minimal computing**: A design philosophy that builds digital tools for the hardware and connectivity scholars actually possess, rather than the infrastructure available at well-resourced institutions (Gil and Ortega 2016).
- **WebGL**: A JavaScript API for rendering interactive 2D and 3D graphics within web browsers, used by ImageSpace via PixiJS to render over 50,000 image sprites at interactive frame rates.

---

## References

Agarwal, S., Krueger, G., Clark, J., Radford, A., Kim, J. W., and Brundage, M. 2021. "Evaluating CLIP: Towards Characterization of Broader Capabilities and Downstream Risks." arXiv:2108.02818.

Anzt, H., Bach, F., Druskat, S., Löffler, F., Loewe, A., Renber, B. Y., Seemann, G., et al. 2020. "An Environment for Sustainable Research Software in Germany and Beyond: Current State, Open Challenges, and Call for Action." *F1000Research* 9: 295.

Arnold, T., and Tilton, L. 2023. *Distant Viewing: Computational Exploration of Digital Images*. Cambridge, MA: MIT Press.

Arnold, T., Tilton, L., and Berber, A. 2020. "Visualizing a Large Spatiotemporal Collection of Historic Photography with a Generous Interface." In *Proceedings of the International Conference on Computational Creativity*.

Asperti, A., Barro, D., and Nardelli, M. 2025. "Does CLIP Perceive Art the Same Way We Do?" *Multimedia Tools and Applications*.

Berryman, J. 2024. "Creativity and Style in GAN and AI Art." *Leonardo*.

Campello, R. J. G. B., Moulavi, D., and Sander, J. 2013. "Density-Based Clustering Based on Hierarchical Density Estimates." In *Advances in Knowledge Discovery and Data Mining (PAKDD)*, edited by J. Pei et al., 160–172. Berlin: Springer.

Drucker, J. 2013. "Is There a 'Digital' Art History?" *Visual Resources* 29 (1–2): 5–13.

Duhaime, D. 2019. PixPlot. Yale Digital Humanities Lab. https://github.com/YaleDHLab/pix-plot.

Gil, A., and Ortega, É. 2016. "Global Outlooks in Digital Humanities: Multilingual Practices and Minimal Computing." In *Doing Digital Humanities: Practice, Training, Research*, edited by C. Crompton, R. J. Lane, and R. Siemens, 22–34. London: Routledge.

Glinka, K., Pietsch, C., and Dörk, M. 2017. "Past Visions and Reconciling Views: Visualizing Time, Texture, and Themes in Cultural Collections." *Digital Humanities Quarterly* 11 (2).

Guo, P. 2021. "Ten Million Users and Ten Years Later: Python Tutor's Design Guidelines for Building Scalable and Sustainable Research Software in Academia." In *Proceedings of the 34th Annual ACM Symposium on User Interface Software and Technology*, 1235–1251.

Huang, Y., and Lee, B. 2025. "Digital Collections Explorer: Enabling Multimodal Search and Exploration of Open-Access Digital Archives." *Digital Scholarship in the Humanities*.

Impett, L., and Offert, F. 2024. "There Is a Digital Art History." In *Handbook of Digital Art History*, edited by K. Brown. London: Routledge.

Konkol, M., Nüst, D., and Goulier, L. 2020. "Publishing Computational Research — A Review of Infrastructures for Reproducible and Transparent Scholarly Communication." *Research Integrity and Peer Review* 5: 10.

Manovich, L. 2012. "How to Compare One Million Images?" In *Understanding Digital Humanities*, edited by D. M. Berry, 249–278. London: Palgrave Macmillan.

Moretti, F. 2013. *Distant Reading*. London: Verso.

Policar, P. G., Stražar, M., and Zupan, B. 2019. "openTSNE: A Modular Python Library for t-SNE Dimensionality Reduction and Embedding." bioRxiv. doi:10.1101/731877.

Radford, A., Kim, J. W., Hallacy, C., Ramesh, A., Goh, G., Agarwal, S., Sastry, G., et al. 2021. "Learning Transferable Visual Models from Natural Language Supervision." In *Proceedings of the 38th International Conference on Machine Learning*, 8748–8763.

Rashtchian, C., Feng, R., and Sameki, M. 2023. "Substance or Style: What Does Your Image Embedding Know?" In *Proceedings of the IEEE/CVF International Conference on Computer Vision Workshops*.

Saleh, B., and Elgammal, A. 2015. "Large-scale Classification of Fine-Art Paintings: Learning the Right Metric on the Right Feature." *International Journal for Digital Art History* 2: 70–93.

Strafforello, O., van Noord, N., Wiggers, A., and Worring, M. 2024. "Have Large Vision-Language Models Mastered Art History?" *Digital Scholarship in the Humanities*.

van der Maaten, L., and Hinton, G. 2008. "Visualizing Data Using t-SNE." *Journal of Machine Learning Research* 9: 2579–2605.

Wasielewski, A. 2021. "Growing Pains of Digital Art History." *Visual Resources* 37 (3–4): 179–188.

Wasielewski, A. 2023. *Computational Formalism: Art History and Machine Learning*. Cambridge, MA: MIT Press.

Whitelaw, M. 2015. "Generous Interfaces for Digital Cultural Collections." *Digital Humanities Quarterly* 9 (1).

Ye, J., Xu, M., Wu, Z., and Liu, Y. 2024. "VISAtlas: Visualizing Image Collections at Scale with Neural Embeddings." In *Proceedings of IEEE VIS*.
"""

path = f"{ARTICLE_DIR}/draft.md"
with open(path, 'w') as f:
    f.write(draft)
print(f"Written draft.md: {len(draft)} chars")

# Quick word count (approximate)
words = len(draft.split())
print(f"Approximate word count: {words}")

if __name__ == "__main__":
    pass
